### ISSUE TITLE
Vim Motions

### ISSUE THREAD

**Issue by diego-rapoport** [Julien-cpsn/ATAC#10]
Is it planned to have Vim motions in general navigation and editing?

**Comment by Julien-cpsn** [comment]
Hello!
Yes it is in the things planned for after v1.0.0 (which will comme soon).
A thing I was wondering since I am not a vim user, do you means "command-like" bindings e.g. `:wq`, or just the key binding?

**Comment by diego-rapoport** [comment]
Hi!

I was first thinking about vim motions like `hjkl` as arrow keys to move arround, even to replace `TAB` as moving. Maybe have something like vim mode as `INSERT` to edit the url and then come back to `NORMAL` so you can keep moving.
Command-like bindings sounds good too but I can't think right now how it could do usefull things.

**Comment by brandon1024** [comment]
I would love to see this too. I use Vim as my primary editor and vim motions feel so natural to me, so I initially had a hard time playing around with `atac`.

**Comment by mzndr** [comment]
Ideally you would navigate with `hjkl` instead of arrow keys. Whenever you have to delete something, you'd usually add `dd` as an input for that. Editing request bodies etc. should also also mimic vim to a reasonable extend. It would be great to enable a workflow where you can use actual vim for editing requests, but to be honest, I haven't looked into the file structure that `atac` generates yet, maybe its possible to raw-dog these files with nvim.

The basics for navigation would be:
`hjkl` instead of arrow keys
`dd` to delete stuff
`CTRL + D or CTRL + U` to navigate up/down a bunch
`/` to search for stuff.

I think `lazygit` has a good implementation, `btm` also comes to mind.

**Comment by Julien-cpsn** [comment]
> Ideally you would navigate with `hjkl` instead of arrow keys. Whenever you have to delete something, you'd usually add `dd` as an input for that. Editing request bodies etc. should also also mimic vim to a reasonable extend. It would be great to enable a workflow where you can use actual vim for editing requests, but to be honest, I haven't looked into the file structure that `atac` generates yet, maybe its possible to raw-dog these files with nvim.
> 
> A great start would be something like this: `hjkl` instead of arrow keys `dd` to delete stuff `CTRL + D or CTRL + U` to navigate up/down a bunch `/` to search for stuff.
> 
> I think `lazygit` has a good implementation, `btm` also comes to mind.

I am currently working on it in https://github.com/Julien-cpsn/ATAC/tree/10-vim-motions.

The implemenation will be simple at first.
And I will try to make the full bindings implemenation on the request body text area.

**Comment by mzndr** [comment]
Thats great! I'll happily test that feature and provide feedback.

Trying to implement the full range vim motions in the text area might be way too much (unless theres a library for that or something), since theres a lot of more complex features that vim users frequently rely on (for examlple `ci"`, `da}`, `dap`, `caW`), so don't aim too high. It might be better to implement the basics, and enable a workflow where one can use their editor of choice to edit requests.

**Comment by mzndr** [comment]
Sounds great, I'll make sure to check it out once its done to provide feedback! A lot of vim is muscle memory, so its always hard to tell whats missing before you actually use it. But lets be honest, even basic vim motions would be a huge improvement for vim users, and its really great that you're working on it. Love to see it, much love

**Comment by Julien-cpsn** [comment]
@mzndr @brandon1024 @diego-rapoport 
Hello guys!

I have been working on the configurable key-bindings and Vim implementation for the last 20 hours (no joke)
Since it reworks most the application's key and event systems, I would like some people to test it before pushing into prod.

All the code is here: https://github.com/Julien-cpsn/ATAC/tree/10-vim-motions

You can pull it. At first you will see that almost nothing has changed.
If you want to enable the "Vim config" you have to set the `ATAC_KEY_BINDINGS` env variable to a key-bindings config file. Luckily I made one for Vim users in `key_bindings_templates/vim_key_bindings.toml`. I am not a vim user so it may not perfect.

If you struggle finding keys etc, you can press `Ctrl-h` (or `Shift-h` with the Vim config) from anywhere to display the key-bindings help

Also, if you have any question, do not hesitate

Enjoy!

**Comment by kayuxx** [comment]
@Julien-cpsn, the Vim implementation is great! However, I noticed that the backspace key doesn't work when entering the URL field.

**Comment by Julien-cpsn** [comment]
@kayuxx is your backspace problem resolved? (when editing the URL)

**Comment by diego-rapoport** [comment]
Hey @Julien-cpsn!!
Thanks for your time and work for this feature. I know that many devs who works directly on the terminal would love some vim keybindings.
I tested a bit and the side panel with the collections are very good just as editing the body request. Just what I expected.
Haven't tried the cookies part but the keybindings seems good either.

Still getting used to it, but most of default keybinds were already good like `u` for editing the URL. `a` to change auth and `t` for tab. Also no need to delete with the `x` key on the URL, but move around with `Ctrl h` and `Ctrl l` is very helpfull.

I could think of another good key: `ciw` as _change inside word_

I had some difficulties trying to edit the value ofparams.

If you want me to test some other things I'd be very glad to help!

**Comment by Julien-cpsn** [comment]
Thanks for your precious feedback!

I did some changes regarding what @ndtoan96 said here https://github.com/Julien-cpsn/ATAC/pull/44/files and my personnal thoughts.
You can pull the branch to get those updates!

Here are the updates:
- delete_forward was x and is now Backspace
- added alt_move_cursor for generic navigation (the k j inputs were never received as a reel char input while creating a request, because it was used for selecting a collection):
```
# Used when the base keys are not available (Selecting collection while creating a new request)
# Might not happen when using the default config
alt_move_cursor_up = "Ctrl-k"
alt_move_cursor_down = "Ctrl-j"
alt_move_cursor_left = "Ctrl-h"
alt_move_cursor_right = "Ctrl-l"
```

> Still getting used to it, but most of default keybinds were already good like `u` for editing the URL. `a` to change auth and `t` for tab. Also no need to delete with the `x` key on the URL, but move around with `Ctrl h` and `Ctrl l` is very helpfull.

The x key has been fixed!

> I could think of another good key: `ciw` as _change inside word_
> I had some difficulties trying to edit the value of params.

Actually, the c keycame from `cw` but it's really not that practical, and I *cannot* implement multi-key combinations such as ciw. So choose another :)) (temporarily set to Enter)

> If you want me to test some other things I'd be very glad to help!

I am begging you to do so 😆

**Comment by NachoNievaG** [comment]
This would be a natural UX enhancement as TUI apps (like LazyGit) already have some sort of vim navigations at least.
Not necessarily related, I made a floating term client for ATAC inside [neovim](https://github.com/NachoNievaG/atac.nvim), so hopefully the vim motions inside ATAC + nvim plugin will make a fairly comfortable combo.

**Comment by Julien-cpsn** [comment]
> This would be a natural UX enhancement as TUI apps (like LazyGit) already have some sort of vim navigations at least.

Read 3 messages before this one in order to test it out hahah. I wrote down the procedure 

> Not necessarily related, I made a floating term client for ATAC inside [neovim](https://github.com/NachoNievaG/atac.nvim), so hopefully the vim motions inside ATAC + nvim plugin will make a fairly comfortable combo.

Very good! Can I put it in my readme ?

**Comment by Julien-cpsn** [comment]
@NachoNievaG very great!
Main branch is great

**Comment by kayuxx** [comment]
@Julien-cpsn Yeah, it works. I just checked the keybindings and it was mapped to `x` instead of `Backspace`, so I remapped it and it works fine. Thank you for the feature!

**Comment by Julien-cpsn** [comment]
@kayuxx is it ready for production you think?

**Comment by kayuxx** [comment]
@Julien-cpsn Yes, I think it's ready to be used. It just has one thing to do. It would be great to implement these Vim keybindings #44.

**Comment by javeoff** [comment]
how to apply this changes? I cant find any information about configuration. Where is the config?

**Comment by NachoNievaG** [comment]
@javeoff:
inside this repository you can use the example resource file for vim keybindings and follow the next steps:
1. Copy the file/content from [example_resources/key_bindings/vim_key_bindings.toml](https://github.com/Julien-cpsn/ATAC/blob/main/example_resources/key_bindings/vim_key_bindings.toml).
2. Save in somewhere accesible, `~/.config/atac/vim_key_bindings.toml` follows the "usual" TUI configuration file practice.
3. Set the `ATAC_KEY_BINDINGS` env var with the route to you configuration file, in this case: `~/.config/atac/vim_key_bindings.toml`.
4. Open ATAC to test it out.

Hope this helps.

**Comment by ovidius72** [comment]
Can we use a global config file instead of the env variable ? Such as ~/.config/atac/config.toml or something like that ?

**Comment by kakapt** [comment]
> Can we use a global config file instead of the env variable ? Such as ~/.config/atac/config.toml or something like that ?

^ This

**Comment by Julien-cpsn** [comment]
It is possible to have a global config file by setting a `global.toml` file 

For more info, see:
https://github.com/Julien-cpsn/ATAC/releases/tag/v0.23.0

Have a great day

**Comment by kakapt** [comment]
> It is possible to have a global config file by setting a `global.toml` file
> 
> For more info, see: https://github.com/Julien-cpsn/ATAC/releases/tag/v0.23.0
> 
> Have a great day

It does not work when I remove the   `ATAC_KEY_BINDINGS` and place all of the keybinds config in `~/.config/atac/global.toml`. The `config.rs` does not read these keybind settings  `key_bindings.rs` use the default if the env is not provided! [files](https://github.com/Julien-cpsn/ATAC/tree/main/src/app/files)

**Comment by Julien-cpsn** [comment]
`~/.config/atac/global.toml` serves for global config file, not key bindings
`ATAC_KEY_BINDINGS` serves for global key bindings, not config

**Comment by kakapt** [comment]
> `~/.config/atac/global.toml` serves for global config file, not key bindings `ATAC_KEY_BINDINGS` serves for global key bindings, not config

I mean how to set global key bindings without using `ATAC_KEY_BINDINGS`

**Comment by Julien-cpsn** [comment]
@kakapt I don't think that is possible by now.

I don't know if it matches your problem but you can style use `ATAC_KEY_BINDINGS=xxxxxx.toml atac`, so you don't need to `export ATAC_KEY_BINDINGS`

**Comment by kakapt** [comment]
> [@kakapt](https://github.com/kakapt) I don't think that is possible by now.
> 
> I don't know if it matches your problem but you can style use `ATAC_KEY_BINDINGS=xxxxxx.toml atac`, so you don't need to `export ATAC_KEY_BINDINGS`

I think that would be better if atac let the user choose which keybindings file to use in the global config file! Typing `ATAC_KEY_BINDINGS=xxxxxx.toml atac` seems wrong to me because you know the users only stick to 1 set of keybinds most of the time!

**Comment by Julien-cpsn** [comment]
I get your point, but I don't get why you do not `export ATAC_KEY_BINDINGS=<my_file>`
