### ISSUE TITLE
Unsure about the scripting feature

### ISSUE THREAD

**Issue by Cephra** [Julien-cpsn/ATAC#90]
Hello,

firstly I wanna say that I really like how ATAC performs. After getting used to the keybindings it was super easy!

I'm now wondering how the scripting feature works (exposed variables, etc.). 

It seems that part is missing in the docs or at least I couldn't find it.
I could only find the reference to the boa engine.

Greetings,

Chris

**Comment by Julien-cpsn** [comment]
@Cephra 

Hello man, thank you!!

Yes, writing documentation is very long and boring sadly

The scripting feature is based on the JS VM/runtime boa (as you already said). It will run you script isolated from the rest of the codebase in order to avoid security issues.

The runtime you get access to is very basic and does not include a lot of things (it's made on purpose). For exemple, I did re-code console.log() my self. If you need a special feature to be added regarding the runtime, ask me and I'll think of adding it. Someone recently talked about adding http-module resolution, which can be a good idea if it doesn't go against the original goal.

Regarding your question, what you get access to is a JSON version of the preparated request (or response) and the current environment. Those variables are set whith a bunch of utils (as previously stated) before executing your script.

Taka a look to what's going on in reality :

```js
let request = {request_json};
let env = {env_json};

/* Utils */

let console_log_output = "";

globalThis.console = {
  log: (msg) => {
    console_log_output += msg + '\n';
    return msg;
  }
}

function pretty_print(data) {
      console.log(JSON.stringify(data, null, 2));
}

/* Start of the user script */

{user_script}

/* End of the user script */

JSON.stringify([request, env, console_log_output])
```

Then, I retrieve the modified variables and turn them back to Rust.

Here is the Rust struct and the field you can get access to:
```rust
#[derive(Default, Debug, Clone, Serialize, Deserialize)]
pub struct Request {
    pub name: String,
    pub url: String,
    pub method: Method,
    pub params: Vec<KeyValue>,
    pub headers: Vec<KeyValue>,
    pub body: ContentType,
    pub auth: Auth,
    pub scripts: RequestScripts,
    pub settings: RequestSettings,

    #[serde(skip)]
    pub response: RequestResponse,

    #[serde(skip)]
    pub is_pending: bool
}
```

PS: Note that serde_skip says that this specific field will not be parsed or serialized

If you have any other questions, do not hesitate!

Have a great day

**Comment by Cephra** [comment]
Wow, thanks for the timely response! I will close this issue now and play around with it a bit. If I have any further questions, I will just re-open or create another issue if need be. Thanks, man!

**Comment by Julien-cpsn** [comment]
https://atac.julien-cpsn.com/docs/tui/request/scripts
